name: Update Clang Prebuilts

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

permissions:
  contents: write
  actions: read

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */3 * * *'

jobs:
  update:
    runs-on: ubuntu-slim

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6.0.3
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Set up uv
        uses: astral-sh/setup-uv@v8.2.0
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync --locked

      - name: Fetch latest Clang
        run: uv run app.py fetch

      - name: Create release
        env:
          GH_TOKEN: ${{ github.token }}
        run: uv run app.py release

      - name: Send Telegram notification
        env:
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
        run: uv run app.py notify
